# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scancodelogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(blank=True, default='', max_length=50, verbose_name='\u7528\u6237id')),
                ('sid', models.CharField(blank=True, default='', max_length=50, verbose_name='\u626b\u7801\u552f\u4e00\u6807\u8bc6')),
            ],
            options={
                'verbose_name': '\u626b\u7801\u767b\u9646',
                'verbose_name_plural': '\u626b\u7801\u767b\u9646',
            },
        ),
    ]
