# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-21 11:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('key', models.CharField(blank=True, default='', max_length=50, verbose_name='\u626b\u7801\u552f\u4e00\u6807\u8bc6')),
                ('owner', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u626b\u7801\u767b\u9646',
                'verbose_name_plural': '\u626b\u7801\u767b\u9646',
            },
        ),
        migrations.DeleteModel(
            name='Scancodelogin',
        ),
    ]
