# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-21 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20161221_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrtoken',
            name='status',
            field=models.CharField(blank=True, choices=[('error', '\u5931\u8d25'), ('success', '\u6210\u529f')], max_length=50, verbose_name='\u767b\u5f55\u72b6\u6001'),
        ),
    ]
