# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-21 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_remove_qrtoken_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrtoken',
            name='status',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='\u767b\u5f55\u72b6\u6001'),
        ),
    ]
