# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 19:20
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_auto_20161222_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrtoken',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='qrtoken',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='qrtoken',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='init', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='qrtoken',
            name='status_changed',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed'),
        ),
    ]
