# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-21 04:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_qrtoken_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrtoken',
            name='status',
        ),
    ]
