# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 00:45
from __future__ import unicode_literals

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_auto_20161221_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrtoken',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='scan', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
    ]
