# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-23 01:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_qrtokenfds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrtokenfds',
            name='owner',
        ),
        migrations.DeleteModel(
            name='QRTokenfds',
        ),
    ]
