# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 04:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trade', '0002_auto_20161205_0128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='transaction_amount',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='consumption_business',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='consumption_commodity',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='consumption_type',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='date',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='into_AccountNumber',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='into_name',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='turnOut_AccountNumber',
        ),
        migrations.AddField(
            model_name='contract',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='contract',
            name='make_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u64cd\u4f5c\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='contract',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='contract',
            name='receiver',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='sender',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='summary',
            field=models.CharField(default=django.utils.timezone.now, max_length=300, verbose_name='\u539f\u56e0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='type',
            field=models.CharField(choices=[('receipt', '\u6536\u636e'), ('borrow', '\u501f\u6761'), ('owe', '\u6b20\u6761')], default=0, max_length=100, verbose_name='\u6d88\u8d39\u7c7b\u578b'),
        ),
    ]
