# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 05:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trade', '0003_auto_20161213_0457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('type', models.CharField(choices=[('receipt', '\u6536\u636e'), ('borrow', '\u501f\u6761'), ('owe', '\u6b20\u6761')], default=0, max_length=100, verbose_name='\u6d88\u8d39\u7c7b\u578b')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='\u4ea4\u6613\u91d1\u989d')),
                ('summary', models.CharField(max_length=300, verbose_name='\u539f\u56e0')),
                ('transfer', models.CharField(default='', max_length=100, verbose_name='\u8f6c\u51fa\u94f6\u884c\u5361')),
                ('receiver', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='transfer_receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='transfer_sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u6d88\u8d39\u8bb0\u5f55',
                'verbose_name_plural': '\u6d88\u8d39\u8bb0\u5f55',
            },
        ),
        migrations.RemoveField(
            model_name='consumption',
            name='owner',
        ),
        migrations.AlterField(
            model_name='contract',
            name='receiver',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='contract_receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contract',
            name='sender',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='contract_sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Consumption',
        ),
    ]
