# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_auto_20161213_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='mobile',
            field=models.CharField(default='', max_length=100, verbose_name='\u624b\u673a\u53f7'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='mobile',
            field=models.CharField(default='', max_length=100, verbose_name='\u624b\u673a\u53f7'),
        ),
    ]
