# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 21:15
from __future__ import unicode_literals

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0011_auto_20161221_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='normal', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
    ]
