# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 01:25
from __future__ import unicode_literals

from django.db import migrations, models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0013_purchased'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='payment',
            field=models.CharField(default='', max_length=100, verbose_name='\u652f\u4ed8\u8d26\u6237'),
        ),
        migrations.AddField(
            model_name='contract',
            name='receipt',
            field=models.CharField(default='', max_length=100, verbose_name='\u6536\u6b3e\u8d26\u6237'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='normal', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
    ]
