# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0014_auto_20161226_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='type',
            field=models.CharField(choices=[('transfer', '\u8f6c\u8d26'), ('receiver', '\u6536\u6b3e'), ('thirty', '\u7b2c\u4e09\u65b9\u652f\u4ed8'), ('receipt', '\u6536\u636e'), ('borrow', '\u501f\u6761'), ('owe', '\u6b20\u6761')], default=0, max_length=100, verbose_name='\u6d88\u8d39\u7c7b\u578b'),
        ),
    ]
