# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0016_auto_20161226_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='orderid',
            field=models.CharField(default='', max_length=200, verbose_name='\u5355\u53f7'),
        ),
    ]
