# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 04:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0018_auto_20170105_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='receiver_sign',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_sign', to='signature.Signature'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='sender_sign',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_sign', to='signature.Signature'),
        ),
    ]
