# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 03:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0018_auto_20170104_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_receiver', to=settings.AUTH_USER_MODEL),
        ),
    ]
