# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 03:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0019_auto_20170104_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='receiver_sign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_receiver_sign', to='signature.Signature'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='sender_sign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_sender_sing', to='signature.Signature'),
        ),
    ]
