# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-05 21:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0020_auto_20170305_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='status',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='status_changed',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='summary',
        ),
    ]
