# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-05 22:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trade', '0021_auto_20170305_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_owner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
