# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-05 22:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0053_auto_20170305_2147'),
        ('trade', '0022_transfer_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='signaid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_signaid', to='signature.Signature'),
            preserve_default=False,
        ),
    ]
