# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-05 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0023_transfer_signaid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='signaid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='transfer_signaid', to='signature.Signature'),
        ),
    ]
