# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-05 23:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0026_auto_20170305_2324'),
        ('trade', '0020_auto_20170302_0016'),
    ]

    operations = [
    ]
