# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-06 00:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0054_merge_20170305_2328'),
        ('trade', '0027_merge_20170305_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchased',
            name='account',
            field=models.CharField(default='', max_length=100, verbose_name='\u8f6c\u5165\u6237\u540d'),
        ),
        migrations.AddField(
            model_name='purchased',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='\u4ea4\u6613\u91d1\u989d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchased',
            name='bank_accountName',
            field=models.CharField(default=1, max_length=100, verbose_name='\u94f6\u884c\u5f00\u6237\u540d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchased',
            name='consumer',
            field=models.CharField(default='', max_length=100, verbose_name='\u6d88\u8d39\u5546\u5bb6'),
        ),
        migrations.AddField(
            model_name='purchased',
            name='payment',
            field=models.CharField(default='', max_length=100, verbose_name='\u652f\u4ed8\u8d26\u6237'),
        ),
        migrations.AddField(
            model_name='purchased',
            name='receipt',
            field=models.CharField(default='', max_length=100, verbose_name='\u6536\u6b3e\u8d26\u6237'),
        ),
        migrations.AddField(
            model_name='purchased',
            name='signa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='purchased_signaid', to='signature.Signature'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchased',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='\u5546\u54c1\u540d\u79f0'),
        ),
        migrations.AddField(
            model_name='purchased',
            name='type',
            field=models.CharField(choices=[('signin', '\u7b2c\u4e09\u65b9\u767b\u9646'), ('signup', '\u7b2c\u4e09\u65b9\u6ce8\u518c'), ('payment', '\u7b2c\u4e09\u65b9\u652f\u4ed8'), ('receive', '\u7b2c\u4e09\u65b9\u6536\u8d27'), ('refunds', '\u7b2c\u4e09\u65b9\u9000\u8d27'), ('transfer', '\u8f6c\u8d26'), ('receiver', '\u6536\u6b3e'), ('receipt', '\u6536\u636e'), ('borrow', '\u501f\u6761'), ('owe', '\u6b20\u6761')], default=0, max_length=100, verbose_name='\u6d88\u8d39\u7c7b\u578b'),
        ),
    ]
