# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0029_auto_20170306_0102'),
        ('trade', '0027_merge_20170307_2028'),
    ]

    operations = [
    ]
