# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articley',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Banklog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='\u540d\u79f0')),
                ('mobile', models.CharField(default='', max_length=100, verbose_name='\u624b\u673a\u53f7')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='\u4ea4\u6613\u91d1\u989d')),
                ('payment', models.CharField(default='', max_length=100, verbose_name='\u652f\u4ed8\u8d26\u6237')),
                ('receipt', models.CharField(default='', max_length=100, verbose_name='\u6536\u6b3e\u8d26\u6237')),
                ('make_date', models.DateTimeField(blank=True, null=True, verbose_name='\u64cd\u4f5c\u65f6\u95f4')),
                ('order', models.IntegerField(default='1', verbose_name='\u6392\u5e8f')),
            ],
            options={
                'verbose_name': '\u94f6\u884c\u6d41\u6c34',
                'verbose_name_plural': '\u94f6\u884c\u6d41\u6c34',
            },
        ),
    ]
