# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-14 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_remove_banklog_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='banklog',
            name='order',
            field=models.IntegerField(default='1', verbose_name='\u6392\u5e8f'),
        ),
    ]
