# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-20 06:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_banklog_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Articley',
        ),
    ]
