# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-20 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_delete_articley'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banklog',
            name='make_date',
        ),
        migrations.RemoveField(
            model_name='banklog',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='banklog',
            name='name',
        ),
        migrations.RemoveField(
            model_name='banklog',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='banklog',
            name='receipt',
        ),
        migrations.AddField(
            model_name='banklog',
            name='orderid',
            field=models.CharField(default='', max_length=100, verbose_name='\u8ba2\u5355\u53f7\u7801'),
        ),
        migrations.AddField(
            model_name='banklog',
            name='receive',
            field=models.CharField(default=1, max_length=64, verbose_name='\u6536\u6b3e\u65b9\u540d\u5b57'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banklog',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='\u5546\u54c1\u540d\u79f0'),
        ),
    ]
