# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-20 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_remove_banklog_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banklog',
            name='amount',
            field=models.DecimalField(decimal_places=2, default='', max_digits=10, verbose_name='\u4ea4\u6613\u91d1\u989d'),
        ),
        migrations.AlterField(
            model_name='banklog',
            name='receive',
            field=models.CharField(default='', max_length=64, verbose_name='\u6536\u6b3e\u65b9\u540d\u5b57'),
        ),
    ]
