# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterlog',
            name='action',
            field=models.CharField(default='0', max_length=64, verbose_name='\u64cd\u4f5c'),
        ),
    ]
