# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-16 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0002_auto_20170116_0146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waterlog',
            name='action',
        ),
        migrations.RemoveField(
            model_name='waterlog',
            name='stare',
        ),
        migrations.AddField(
            model_name='waterlog',
            name='appkey',
            field=models.CharField(default='', max_length=100, verbose_name='\u64cd\u4f5c'),
        ),
        migrations.AddField(
            model_name='waterlog',
            name='openid',
            field=models.CharField(default='', max_length=100, verbose_name='\u72b6\u6001'),
        ),
    ]
