# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-16 23:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('passport', '0003_auto_20170216_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterlog',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='waterlog',
            name='appkey',
            field=models.CharField(default='', max_length=100, verbose_name='\u552f\u4e00\u6807\u793a'),
        ),
        migrations.AlterField(
            model_name='waterlog',
            name='openid',
            field=models.CharField(default='', max_length=100, verbose_name='\u7528\u6237\u5bf9\u5e94\u7684\u552f\u4e00\u7801'),
        ),
    ]
