# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 16:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0007_auto_20161122_1511'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='contact',
        #     name='default',
        # ),
        migrations.AddField(
            model_name='contact',
            name='friend',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='friend', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        # migrations.AlterField(
        #     model_name='affairs',
        #     name='owner',
        #     field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        # ),
    ]
