# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0008_bankcard_blacklist_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='device',
            field=models.CharField(max_length=100, verbose_name='\u8bbe\u5907\u53f71'),
        ),
    ]
