# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0023_merge_20161212_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='idcard',
            field=models.CharField(default='', max_length=100, verbose_name='\u8eab\u4efd\u8bc1'),
        ),
    ]
