# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0024_profile_idcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bankcard',
            field=models.CharField(default='', max_length=100, verbose_name='\u94f6\u884c\u5361\u53f7'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='\u59d3\u540d'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nick',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='\u6635\u79f0'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='\u94f6\u884c\u9884\u7559\u7535\u8bdd'),
        ),
    ]
