# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 20:18
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0025_auto_20161213_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(default='assets/media/avatar/default.jpg', null=True, upload_to='avatar', verbose_name='\u5934\u50cf'),
        ),
    ]
