# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0026_auto_20161214_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='mobile',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='\u624b\u673a\u53f7'),
        ),
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='\u8054\u7cfb\u4eba'),
        ),
    ]
