# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 21:42
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0027_auto_20161219_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankcard',
            name='cover',
            field=imagekit.models.fields.ProcessedImageField(default='assets/media/bank/default.jpg', null=True, upload_to='bank', verbose_name='LOGO'),
        ),
    ]
