# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 21:47
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0029_auto_20161219_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcard',
            name='cover',
            field=imagekit.models.fields.ProcessedImageField(default='bank/default.jpg', null=True, upload_to='bank', verbose_name='\u94f6\u884clogo'),
        ),
    ]
