# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0030_auto_20161219_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcard',
            name='cover',
            field=imagekit.models.fields.ProcessedImageField(default='banks/default.jpg', null=True, upload_to='bank', verbose_name='\u94f6\u884clogo'),
        ),
        migrations.AlterField(
            model_name='bankcard',
            name='flag',
            field=models.CharField(choices=[('', ''), ('\u6536', '\u6536')], default='', max_length=10, verbose_name='\u5361\u7247\u7528\u9014'),
        ),
        migrations.AlterField(
            model_name='bankcard',
            name='type',
            field=models.CharField(choices=[('\u501f\u8bb0\u5361', '\u501f\u8bb0\u5361'), ('\u8d37\u8bb0\u5361', '\u8d37\u8bb0\u5361')], default='', max_length=10, verbose_name='\u5361\u7247\u7c7b\u578b'),
        ),
    ]
