# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 23:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0032_auto_20161219_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='friend',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='friends', to=settings.AUTH_USER_MODEL, unique=True, verbose_name='\u597d\u53cb'),
        ),
    ]
