# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0034_auto_20161219_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='credit',
            field=models.IntegerField(default='50', verbose_name='\u7528\u6237\u79ef\u5206'),
        ),
    ]
