# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0037_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='type',
            field=models.CharField(choices=[('identity', '\u8ba4\u8bc1'), ('contract', '\u5408\u7ea6'), ('payment', '\u652f\u4ed8'), ('receive', '\u6536\u8d27'), ('refunds', '\u9000\u8d27')], max_length=100, verbose_name='\u6d88\u606f\u7c7b\u578b'),
        ),
    ]
