# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-21 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0039_auto_20170121_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, default='', null=True, verbose_name='\u751f\u65e5'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nick',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, null=True, verbose_name='\u6635\u79f0'),
        ),
    ]
