# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-21 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0041_auto_20170121_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcard',
            name='card',
            field=models.CharField(blank=True, default='', max_length=50, unique=True, verbose_name='\u94f6\u884c\u5361\u53f7'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('', '\u672a\u77e5'), ('male', '\u7537'), ('female', '\u5973')], default='male', max_length=10, verbose_name='\u6027\u522b'),
        ),
    ]
