# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-21 20:48
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0042_auto_20170121_0250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ('pk',), 'verbose_name': '\u6d88\u606f\u4e2d\u5fc3', 'verbose_name_plural': '\u6d88\u606f\u4e2d\u5fc3'},
        ),
        migrations.AddField(
            model_name='notice',
            name='extra',
            field=jsonfield.fields.JSONField(default={'data': None, 'type': None}, verbose_name='\u9644\u52a0\u5185\u5bb9'),
        ),
    ]
