# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-21 21:13
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0044_auto_20170121_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='extra',
            field=jsonfield.fields.JSONField(default={'data': '', 'type': ''}, verbose_name='\u9644\u52a0\u5185\u5bb9'),
        ),
    ]
