# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0010_auto_20161212_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='validate',
            name='nu',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
