# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0011_validate_nu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='certId',
            field=models.CharField(default='', max_length=100, verbose_name='\u8bc1\u4ef6\u53f7 *'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='\u59d3\u540d *'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='phone',
            field=models.CharField(default='', max_length=100, verbose_name='\u7535\u8bdd *'),
        ),
    ]
