# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 02:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0014_auto_20161218_1916'),
        ('signature', '0014_auto_20161218_1941'),
    ]

    operations = [
    ]
