# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0014_auto_20161218_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='identity',
            name='sfb',
            field=models.CharField(default='', max_length=100, verbose_name='\u6d4b\u8bd5\u94f6\u884c\u5361\u53f7'),
        ),
    ]
