# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 02:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0015_identity_sfb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identity',
            name='sfb',
        ),
    ]
