# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 22:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0019_merge_20161222_0144'),
        ('signature', '0016_auto_20161219_0315'),
    ]

    operations = [
    ]
