# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 20:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('signature', '0021_auto_20161222_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchased',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u6d88\u8d39\u8bb0\u5f55',
                'verbose_name_plural': '\u6d88\u8d39\u8bb0\u5f55',
            },
        ),
    ]
