# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0023_auto_20161225_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signature',
            name='created_at',
        ),
        migrations.AddField(
            model_name='signature',
            name='type',
            field=models.CharField(default=1, max_length=100, verbose_name='\u7b7e\u540d\u7c7b\u578b'),
            preserve_default=False,
        ),
    ]
