# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 22:05
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0024_auto_20161225_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='extra',
            field=jsonfield.fields.JSONField(default={}, verbose_name='\u9644\u52a0\u5185\u5bb9'),
        ),
    ]
