# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 02:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0027_auto_20161226_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
