# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0029_auto_20161228_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='level',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='', max_length=100, null=True, verbose_name='\u8ba4\u8bc1\u7ea7\u522b *'),
        ),
    ]
