# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-02 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0033_auto_20161229_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='dn',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='DN'),
        ),
    ]
