# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0035_auto_20170104_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='expired',
            field=models.DateField(blank=True, null=True, verbose_name='\u8fc7\u671f\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='signature',
            name='serial',
            field=models.CharField(default='', max_length=200, verbose_name='\u8bc1\u4e66\u53f7'),
        ),
    ]
