# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-04 19:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0034_auto_20170102_1932'),
        ('signature', '0035_auto_20170104_0230'),
    ]

    operations = [
    ]
