# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-04 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0037_auto_20170104_1906'),
        ('signature', '0036_auto_20170104_0402'),
    ]

    operations = [
    ]
