# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 05:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0039_auto_20170105_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identity',
            name='enddate',
        ),
        migrations.RemoveField(
            model_name='identity',
            name='serial',
        ),
    ]
