# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0040_auto_20170106_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='identity',
            name='enddate',
            field=models.DateField(blank=True, null=True, verbose_name='\u8bc1\u4e66\u8fc7\u671f\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='identity',
            name='serial',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='\u8bc1\u4e66\u7f16\u53f7'),
        ),
    ]
