# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 01:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0043_auto_20170115_2111'),
        ('signature', '0043_auto_20170115_2143'),
    ]

    operations = [
    ]
