# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 01:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0044_auto_20170115_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identity',
            name='secret',
        ),
        migrations.RemoveField(
            model_name='identity',
            name='verify',
        ),
    ]
