# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 20:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0046_auto_20170117_0109'),
        ('signature', '0044_merge_20170116_0146'),
    ]

    operations = [
    ]
