# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 21:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('signature', '0047_merge_20170117_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('secret', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='\u6388\u6743\u7801')),
                ('verify', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='\u9a8c\u8bc1\u7801')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='counter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u4e34\u67dc\u6388\u6743',
                'verbose_name_plural': '\u4e34\u67dc\u6388\u6743',
            },
        ),
        migrations.RemoveField(
            model_name='identity',
            name='secret',
        ),
        migrations.RemoveField(
            model_name='identity',
            name='verify',
        ),
    ]
