# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-21 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0050_auto_20170121_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='enddate',
            field=models.DateField(blank=True, default='1900-01-01', null=True, verbose_name='\u8bc1\u4e66\u8fc7\u671f\u65f6\u95f4'),
        ),
    ]
