# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0052_auto_20170121_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='type',
            field=models.CharField(choices=[('signin', '\u7b2c\u4e09\u65b9\u767b\u9646'), ('signup', '\u7b2c\u4e09\u65b9\u6ce8\u518c'), ('payment', '\u7b2c\u4e09\u65b9\u652f\u4ed8'), ('receive', '\u7b2c\u4e09\u65b9\u6536\u8d27'), ('refunds', '\u7b2c\u4e09\u65b9\u9000\u8d27'), ('transfer', '\u8f6c\u8d26'), ('receiver', '\u6536\u6b3e'), ('receipt', '\u6536\u636e'), ('borrow', '\u501f\u6761'), ('owe', '\u6b20\u6761')], max_length=100, verbose_name='\u7b7e\u540d\u7c7b\u578b'),
        ),
    ]
