# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 20:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0053_auto_20170305_2147'),
        ('signature', '0053_auto_20170302_0016'),
    ]

    operations = [
    ]
