# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0054_merge_20170307_2028'),
        ('signature', '0054_merge_20170305_2328'),
    ]

    operations = [
    ]
