# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_groups_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='cover',
            field=models.ImageField(default=0, upload_to='group', verbose_name='\u7fa4\u7ec4Logo'),
            preserve_default=False,
        ),
    ]
