# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_groups_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='cover',
            field=models.ImageField(default='assets/media/avatar/default.jpg', upload_to='group', verbose_name='\u7fa4\u7ec4Logo'),
        ),
    ]
