# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 20:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0024_bankcard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BankCard',
        ),
    ]
