# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 00:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0028_bankcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('version', models.CharField(default='1.0.0', max_length=10, verbose_name='\u7248\u672c\u53f7')),
                ('install', models.FileField(null=True, upload_to='install', verbose_name='\u5b89\u88c5\u8fde\u63a5')),
                ('sha1sum', models.CharField(max_length=64, verbose_name='\u6587\u4ef6\u9a8c\u8bc1\u7801')),
                ('channel', models.CharField(choices=[('1000', '\u5b98\u7f51'), ('1001', '91\u52a9\u624b'), ('1002', '\u767e\u5ea6'), ('1003', '\u5b89\u5353'), ('1004', '\u8c4c\u8c46\u835a'), ('1005', '\u5e94\u7528\u5b9d'), ('1006', '360'), ('1007', '\u5e94\u7528\u6c47'), ('1008', '\u9b45\u65cf'), ('1009', 'N\u591a\u7f51'), ('1010', 'PP\u52a9\u624b'), ('1011', '\u6dd8\u5b9d'), ('1012', '\u673a\u950b\u7f51'), ('1013', '\u91d1\u7acb'), ('1014', '\u5c0f\u7c73'), ('1015', '\u534e\u4e3a'), ('1016', '\u641c\u72d7'), ('1017', '\u5b89\u667a'), ('1018', '\u6c83\u5546\u5e97'), ('1019', 'itools'), ('1020', '\u7535\u4fe1\u7231\u6e38\u620f'), ('1021', '\u4f18\u4ebf\u5e02\u573a'), ('1022', '\u5e94\u7528\u8d1d'), ('1023', 'googleplay'), ('1024', '\u5b89\u7c89\u7f51')], max_length=10, verbose_name='\u63a8\u5e7f\u6e20\u9053')),
                ('platform', models.CharField(choices=[('ios', 'IOS'), ('android', 'Android')], default='android', max_length=50, verbose_name='APP\u5e73\u53f0')),
            ],
            options={
                'verbose_name': '\u7248\u672c\u5347\u7ea7',
                'verbose_name_plural': '\u7248\u672c\u5347\u7ea7',
            },
        ),
    ]
