# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0029_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='install',
            field=models.URLField(null=True, verbose_name='\u5b89\u88c5\u8fde\u63a5'),
        ),
    ]
