# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 20:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0031_delete_bankcard'),
        ('kernel', '0031_auto_20161223_0220'),
    ]

    operations = [
    ]
