# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 01:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0032_merge_20161225_2115'),
        ('kernel', '0032_merge_20161225_2046'),
    ]

    operations = [
    ]
