# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0033_merge_20161227_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterpriseuser',
            name='appkey',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='APPKEY'),
        ),
        migrations.AddField(
            model_name='enterpriseuser',
            name='secret',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SECRET'),
        ),
    ]
