# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-13 03:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0035_enterpriseuser_callback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certufucate',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Relancement',
        ),
        migrations.DeleteModel(
            name='Transfer',
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
    ]
