# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-16 23:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kernel', '0036_auto_20170213_0317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certufucate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certufucate_num', models.IntegerField(verbose_name='\u8bc1\u4e66\u53f7')),
                ('certufucate_name', models.CharField(max_length=100, verbose_name='\u8bc1\u4e66\u6301\u6709\u4eba')),
                ('credentials_type', models.CharField(choices=[('1110', '\u8eab\u4efd\u8bc1'), ('1111', 'EID'), ('1112', '3')], default=1110, max_length=100, verbose_name='\u8bc1\u4ef6\u7c7b\u578b')),
                ('credentials_num', models.CharField(max_length=100, verbose_name='\u8bc1\u4ef6\u53f7')),
                ('certification_authority', models.CharField(max_length=100, verbose_name='\u53d1\u8bc1\u673a\u6784')),
                ('certufucate_status', models.BooleanField(default=True, verbose_name='\u8bc1\u4e66\u72b6\u6001')),
                ('certufucate_level', models.CharField(choices=[('0', 'A'), ('1', 'B'), ('2', 'C'), ('3', 'D')], default=0, max_length=10, verbose_name='\u8bc1\u4e66\u7b49\u7ea7')),
                ('authentication_mode', models.CharField(choices=[('0', '\u8fdc\u7a0b\u67dc\u53f0'), ('1', '\u94f6\u884c\u67dc\u53f0')], default=0, max_length=10, verbose_name='\u8ba4\u8bc1\u65b9\u5f0f')),
                ('credit_level', models.CharField(choices=[('0', 'A-10'), ('1', 'B-10'), ('2', 'C-10')], max_length=100, verbose_name='\u4fe1\u7528\u7b49\u7ea7')),
                ('termOfValidity', models.DateField(max_length=11, verbose_name='\u6709\u6548\u671f')),
            ],
            options={
                'verbose_name': '\u6570\u5b57\u8bc1\u4e66',
                'verbose_name_plural': '\u6570\u5b57\u8bc1\u4e66',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[(b'sender', b'\xe5\x8f\x91\xe9\x80\x81'), (b'receiver', b'\xe6\x8e\xa5\xe5\x8f\x97')], default=b'sender', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('type', models.CharField(choices=[(b'receipt', b'\xe6\x94\xb6\xe6\x8d\xae'), (b'borrow', b'\xe5\x80\x9f\xe6\x9d\xa1'), (b'owe', b'\xe6\xac\xa0\xe6\x9d\xa1')], default=0, max_length=100, verbose_name='\u6d88\u8d39\u7c7b\u578b')),
                ('mobile', models.CharField(default=b'', max_length=100, verbose_name='\u624b\u673a\u53f7')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='\u4ea4\u6613\u91d1\u989d')),
                ('summary', models.CharField(max_length=300, verbose_name='\u539f\u56e0')),
                ('make_date', models.DateTimeField(blank=True, null=True, verbose_name='\u64cd\u4f5c\u65f6\u95f4')),
                ('receiver', models.ForeignKey(blank=True, default=b'', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, related_name='contract_sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u5408\u7ea6\u8bb0\u5f55',
                'verbose_name_plural': '\u5408\u7ea6\u8bb0\u5f55',
            },
        ),
        migrations.CreateModel(
            name='Relancement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, verbose_name='\u516c\u544a\u6807\u9898')),
                ('content', models.CharField(default='', max_length=200, verbose_name='\u516c\u544a\u5185\u5bb9')),
                ('price', models.ImageField(blank=True, height_field='url_height', help_text='\u56fe\u7247\u5c3a\u5bf8\u6700\u597d\u4e3a75x75', null=True, upload_to='goods', verbose_name='\u56fe\u7247', width_field='url_width')),
                ('applicant', models.CharField(default='', max_length=50, verbose_name='\u7533\u8bf7\u4eba')),
                ('creation_time', models.DateField(auto_now_add=True, verbose_name='\u7533\u8bf7\u65f6\u95f4')),
                ('approval', models.CharField(default='', max_length=50, verbose_name='\u5ba1\u6279\u4eba')),
                ('operation', models.CharField(choices=[('1', '\u5168\u90e8\u64cd\u4f5c\u7cfb\u7edf\u7c7b\u578b'), ('2', 'IOS\u7cfb\u7edf'), ('3', 'Android\u7cfb\u7edf')], max_length=10, verbose_name='\u7528\u6237\u64cd\u4f5c\u7cfb\u7edf\u9650\u5236')),
                ('gender', models.CharField(choices=[('1', '\u5168\u90e8\u6027\u522b'), ('2', '\u7537\u6027\u7528\u6237'), ('3', '\u5973\u6027\u7528\u6237')], max_length=10, verbose_name='\u7528\u6237\u6027\u522b\u9650\u5236')),
                ('age', models.CharField(choices=[('1', '\u5168\u90e8\u5e74\u9f84\u5c42'), ('2', '20~40\u5c81\u7528\u6237'), ('3', '40~60\u5c81\u7528\u6237'), ('4', '60\u5c81\u4ee5\u4e0a\u7528\u6237')], max_length=10, verbose_name='\u7528\u6237\u5e74\u9f84\u9650\u5236')),
                ('authentication', models.CharField(choices=[('1', '\u5168\u90e8\u8ba4\u8bc1\u65b9\u5f0f'), ('2', 'A \u7c7b\u8ba4\u8bc1'), ('3', 'B \u7c7b\u8ba4\u8bc1'), ('4', 'C \u7c7b\u8ba4\u8bc1'), ('5', 'D \u7c7b\u8ba4\u8bc1')], max_length=10, verbose_name='\u7528\u6237\u8ba4\u8bc1\u7c7b\u578b')),
                ('certificates', models.CharField(choices=[('1', '\u5168\u90e8\u8ba4\u8bc1\u7c7b\u578b'), ('2', '\u8eab\u4efd\u8bc1'), ('3', '\u62a4\u7167'), ('4', '\u519b\u5b98\u8bc1'), ('5', '\u53f0\u80de\u8bc1')], max_length=10, verbose_name='\u7528\u6237\u8bc1\u4ef6\u7c7b\u578b')),
                ('approval_status', models.CharField(choices=[('1', '\u5f85\u5ba1\u6838'), ('2', '\u5df2\u53d1\u5e03'), ('3', '\u5df2\u9a73\u56de')], default='1', max_length=10, verbose_name='\u5ba1\u6279\u72b6\u6001')),
                ('applicant_time', models.DateTimeField(auto_now=True, verbose_name='\u5ba1\u6279\u65f6\u95f4')),
                ('order', models.IntegerField(default='1', verbose_name='\u6392\u5e8f')),
            ],
            options={
                'verbose_name': '\u521b\u5efa\u516c\u544a',
                'verbose_name_plural': '\u516c\u544a\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.IntegerField(verbose_name='\u7f16\u53f7')),
                ('transfer_type', models.CharField(choices=[('198', '\u6536\u6b3e'), ('199', '\u8f6c\u8d26')], default=199, max_length=100, verbose_name='\u8f6c\u8d26\u7c7b\u578b')),
                ('transfer_money', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='\u8f6c\u8d26\u91d1\u989d')),
                ('receivables_bank', models.CharField(max_length=30, verbose_name='\u6536\u6b3e\u94f6\u884c')),
                ('receivables_lastNum', models.IntegerField(verbose_name='\u6536\u6b3e\u5c3e\u53f7')),
                ('drawee', models.CharField(max_length=100, verbose_name='\u4ed8\u6b3e\u4eba')),
                ('Payee', models.CharField(default='Null', max_length=100, verbose_name='\u6536\u6b3e\u4eba')),
                ('drawee_bank', models.CharField(max_length=30, verbose_name='\u4ed8\u6b3e\u94f6\u884c')),
                ('drawee_lastNum', models.IntegerField(verbose_name='\u4ed8\u6b3e\u5c3e\u53f7')),
                ('receivables_mark', models.TextField(null=True, verbose_name='\u8f6c\u8d26\u5907\u6ce8')),
                ('application_time', models.DateTimeField(auto_now_add=True, verbose_name='\u7533\u8bf7\u65f6\u95f4')),
                ('receipt_time', models.DateTimeField(auto_now_add=True, verbose_name='\u7b7e\u6536\u65f6\u95f4')),
                ('confirm_transfer', models.BooleanField(default=False, verbose_name='\u786e\u8ba4\u8f6c\u8d26')),
                ('confirm_receipt', models.BooleanField(default=False, verbose_name='\u786e\u8ba4\u6536\u6b3e')),
            ],
            options={
                'verbose_name': '\u8f6c\u8d26\u8bb0\u5f55',
                'verbose_name_plural': '\u8f6c\u8d26\u8bb0\u5f55',
            },
        ),
    ]
