# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-12 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0037_certufucate_contract_relancement_transfer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relancement',
            options={'verbose_name': '\u521b\u5efa\u516c\u544a', 'verbose_name_plural': '\u53d1\u5e03\u516c\u544a'},
        ),
        migrations.AlterField(
            model_name='relancement',
            name='approval_status',
            field=models.CharField(choices=[('1', '\u5f85\u5ba1\u6838'), ('2', '\u5df2\u53d1\u5e03'), ('3', '\u5df2\u9a73\u56de')], default='1', max_length=10, verbose_name='\u516c\u544a\u72b6\u6001'),
        ),
    ]
